"""
LangGraph State Definition (GraphState).

Defines the state structure passed between nodes in the StateGraph workflow.
"""

from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages


class GraphState(TypedDict):
    """LangGraph State representation for the RAG chat workflow.
    
    Fields:
        messages: Conversation turn history (reducer: add_messages appends new messages)
        user_id: Authenticated user ID (extracted from JWT token)
        thread_id: Session ID (for short-term memory checkpointer)
        query: User question string
        retrieved_docs: List of grounding documents [{content, score, source}]
        relevance_ok: Boolean decision flag from decide_node
        answer: Final response string generated by synthesize_node or fallback_node
        model: Selected OpenRouter model ID for LLM synthesis
    """
    messages: Annotated[list, add_messages]
    user_id: str
    thread_id: str
    query: str
    retrieved_docs: list[dict]
    relevance_ok: bool
    answer: str
    model: str
